server:
  port: 8080
  servlet:
    context-path: /seckill

spring:
    # 时区设置
    jackson:
      serialization:
        write-dates-as-timestamps: false
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/seckill?useUnicodeuseUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
     
        username: root
        password: 123456

        hikari.connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #配置初始化大小/最小/最大
        initial-size: 1e
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
    http:
        encoding:
          force: true
          charset: UTF-8
    redis:
        database: 0
        host: 127.0.0.1
        password:
        port: 6379
        jedis:
          pool:
            max-active: 50
            min-idle: 20
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.codeman.seckill.entity/*.java
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    height: 80
    width: 80
  tracker-list[0]: